### ISSUE TITLE
"Related items" thumbnail images not showing

### ISSUE THREAD

**Issue by lamminmaki** [UncommonUnion/WCV#40]
Some related items do not show the image thumbnail. For example, see: https://dev-constitution-making-for-peace.pantheonsite.io/peace-through-diversity-and-inclusive-constitution-making/) and the attached image. 
![related items thumbnails](https://cloud.githubusercontent.com/assets/19553399/17736032/c799810a-6485-11e6-8c86-288ad9a5e2a4.png)

**Comment by UncommonUnion** [comment]
You need to designate a featured image for a thumbnail to show up. So just add a featured image at it will appear. I did this for your example to illustrate.

Side note: that the visibility of the featured image CAN be toggled for viewing the full post. There is a visibility checkmark on the edit page. This way you can have a video be at the top of the post (embedded in the body text) and not have the feature image be rendered too - it will otherwise automatically appear at the top of the post. There may be other scenarios in which you do not want the feature image to appear in the post too. I think whoever set up the video pages may not have noticed the check box and this is the basis of the issue reported here.

**Comment by lamminmaki** [comment]
Great - thank you!
